### ISSUE TITLE
Application cannot be scheduled normally

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/local-storage#108]
Application cannot be scheduled normally
![图片](https://user-images.githubusercontent.com/76234281/172088283-663fee10-2a7a-4675-846f-bd22563b822a.png)
![图片](https://user-images.githubusercontent.com/76234281/172088292-ff5cc147-bf24-4112-8ca1-f1c6b6820902.png)
![图片](https://user-images.githubusercontent.com/76234281/172088299-f9e49bf3-0e43-4f82-aefe-1b1af3bfc9ee.png)
LDC available

**Comment by angel0507** [comment]
thanks for your issue, we had fixed it already , plz refer to links as follows 
https://github.com/hwameistor/local-storage/pull/114
