### ISSUE TITLE
pvc info still remained in lsn after lv/lvr deleted

### ISSUE THREAD

**Issue by zhaosimon** [hwameistor/local-storage#125]
I created a statefulSet with pods running, and each pod attached with lv/lvr.

After I deleted the statefulSet, pods, and lv/lvrs, the pvc volume info still remained in 'kubectl get lsn -o yaml'  

![Uploading 屏幕快照 2022-06-23 下午5.17.00.png…]()

**Comment by angel0507** [comment]
thanks for your issue , we found it indeed a bug, we had fixed it in newer version already . plz  try test it again with newer version.

**Comment by angel0507** [comment]
relevant issue is:
https://github.com/hwameistor/local-storage/pull/127

**Comment by zhaosimon** [comment]
Thanks, Bug fixed!
