### ISSUE TITLE
lsn status is 'offline'

### ISSUE THREAD

**Issue by zhaosimon** [hwameistor/local-storage#139]
lsn status is 'offline'
<img width="708" alt="屏幕快照 2022-06-30 下午4 00 43" src="https://user-images.githubusercontent.com/36882380/176789917-d1752a43-62c2-406d-89f1-8a20e3c5118f.png">

**Comment by angel0507** [comment]
Check your environment‘s system clock synchronized or not. This will effect the lsn status .

**Comment by zhaosimon** [comment]
Thanks! the problem solved after time syncronization!
