### ISSUE TITLE
exec cmd "go mod tidy" error

### ISSUE THREAD

**Issue by jiuker** [hwameistor/local-storage#31]
Brach:
 ```master```
Error:
 ```github.com/stretchr/objx: github.com/hwameistor/local-disk-manager@v0.0.0-00010101000000-000000000000 (replaced by ../local-disk-manager): reading ../local-disk-manager/go.mod: open /Users/xxxx/xxxxx/go/src/local-disk-manager/go.mod: no such file or directory```

**Comment by angel0507** [comment]
@jiuker If you modify go.mod by execing `replaced by ../local-disk-manager`, you should clone local-disk-manager project first  located at  "/Users/xxxx/xxxxx/go/src/local-disk-manager" .

**Comment by jiuker** [comment]
> @jiuker If you modify go.mod by execing `replaced by ../local-disk-manager`, you should clone local-disk-manager project first located at "/Users/xxxx/xxxxx/go/src/local-disk-manager" .

It already exists in go.mod。

**Comment by angel0507** [comment]
@jiuker I think you should update your code . it has been modified in latest main branch .

**Comment by jiuker** [comment]
> @jiuker I think you should update your code . it has been modified in latest main branch .

https://github.com/hwameistor/local-storage/blob/main/go.mod
Still exist
```
replace(
...
	github.com/hwameistor/local-disk-manager => ../local-disk-manager
	github.com/hwameistor/local-storage => ../local-storage
...
)
```

**Comment by angel0507** [comment]
@jiuker  forget to merge it . try again

**Comment by jiuker** [comment]
> @jiuker forget to merge it . try again

Ok。It's done!
