### ISSUE TITLE
go 1.16 would select

### ISSUE THREAD

**Issue by jiuker** [hwameistor/local-storage#32]
Hi, My go version is `go version go1.18rc1 darwin/amd64`,when I exec 'go mod tidy'(After I clone github.com/hwameistor/local-disk-manager)，I got this:

```
go: downloading github.com/onsi/ginkgo v1.12.1
go: downloading github.com/onsi/gomega v1.10.1
go: downloading k8s.io/apiextensions-apiserver v0.18.6
go: downloading github.com/kr/pretty v0.1.0
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.9.5
go: downloading github.com/tmc/grpc-websocket-proxy v0.0.0-20170815181823-89b8d40f7ca8
go: downloading go.etcd.io/bbolt v1.3.3
go: downloading github.com/gorilla/websocket v1.4.0
go: downloading golang.org/x/lint v0.0.0-20190930215403-16217165b5de
go: downloading golang.org/x/tools v0.1.1
go: downloading golang.org/x/mod v0.4.2
go: downloading sigs.k8s.io/structured-merge-diff v0.0.0-20190525122527-15d366b2352e
go: downloading github.com/docker/docker v1.4.2-0.20200203170920-46ec8731fbce
go: downloading google.golang.org/genproto v0.0.0-20200117163144-32f20d992d24
go: downloading go.etcd.io/bbolt v1.3.4
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.12.1
go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.1.0
github.com/hwameistor/local-storage/cmd/scheduler imports
        k8s.io/kubernetes/cmd/kube-scheduler/app imports
        github.com/spf13/cobra loaded from github.com/spf13/cobra@v0.0.5,
        but go 1.16 would select v1.0.0
github.com/hwameistor/local-storage/cmd/scheduler imports
        k8s.io/kubernetes/cmd/kube-scheduler/app imports
        k8s.io/apiserver/pkg/util/term imports
        github.com/docker/docker/pkg/term loaded from github.com/docker/docker@v0.7.3-0.20190327010347-be7ac8be2ae0,
        but go 1.16 would select v1.4.2-0.20200203170920-46ec8731fbce
github.com/hwameistor/local-storage/pkg/member/csi imports
        github.com/container-storage-interface/spec/lib/go/csi imports
        google.golang.org/grpc/status imports
        google.golang.org/genproto/googleapis/rpc/status loaded from google.golang.org/genproto@v0.0.0-20191220175831-5c49e3ecc1c1,
        but go 1.16 would select v0.0.0-20200117163144-32f20d992d24
github.com/hwameistor/local-storage/pkg/scheduler imports
        k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
        k8s.io/component-base/metrics imports
        github.com/blang/semver loaded from github.com/blang/semver@v3.5.0+incompatible,
        but go 1.16 would select v3.5.1+incompatible
github.com/hwameistor/local-storage/cmd/scheduler imports
        k8s.io/kubernetes/cmd/kube-scheduler/app imports
        k8s.io/apiserver/pkg/server/routes imports
        k8s.io/kube-openapi/pkg/handler imports
        github.com/NYTimes/gziphandler loaded from github.com/NYTimes/gziphandler@v0.0.0-20170623195520-56545f4a5d46,
        but go 1.16 would select v1.1.1
github.com/hwameistor/local-storage/cmd/scheduler imports
        k8s.io/kubernetes/cmd/kube-scheduler/app imports
        k8s.io/apiserver/pkg/util/term imports
        github.com/docker/docker/pkg/term imports
        github.com/docker/docker/pkg/term/windows loaded from github.com/docker/docker@v0.7.3-0.20190327010347-be7ac8be2ae0,
        but go 1.16 would select v1.4.2-0.20200203170920-46ec8731fbce
github.com/hwameistor/local-storage/pkg/member/csi imports
        github.com/container-storage-interface/spec/lib/go/csi imports
        google.golang.org/grpc/codes tested by
        google.golang.org/grpc/codes.test imports
        google.golang.org/genproto/googleapis/rpc/code loaded from google.golang.org/genproto@v0.0.0-20191220175831-5c49e3ecc1c1,
        but go 1.16 would select v0.0.0-20200117163144-32f20d992d24
github.com/hwameistor/local-storage/pkg/member/csi imports
        github.com/container-storage-interface/spec/lib/go/csi imports
        google.golang.org/grpc/status tested by
        google.golang.org/grpc/status.test imports
        google.golang.org/genproto/googleapis/rpc/errdetails loaded from google.golang.org/genproto@v0.0.0-20191220175831-5c49e3ecc1c1,
        but go 1.16 would select v0.0.0-20200117163144-32f20d992d24
github.com/hwameistor/local-storage/pkg/scheduler imports
        k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
        k8s.io/kubernetes/pkg/controller/volume/scheduling imports
        k8s.io/apiserver/pkg/storage/etcd3 tested by
        k8s.io/apiserver/pkg/storage/etcd3.test imports
        github.com/coreos/pkg/capnslog loaded from github.com/coreos/pkg@v0.0.0-20180108230652-97fdf19511ea,
        but go 1.16 would select v0.0.0-20180928190104-399ea9e2e55f
github.com/hwameistor/local-storage/cmd/alerter imports
        sigs.k8s.io/controller-runtime/pkg/client/config tested by
        sigs.k8s.io/controller-runtime/pkg/client/config.test imports
        sigs.k8s.io/controller-runtime/pkg/log/zap imports
        go.uber.org/zap tested by
        go.uber.org/zap.test imports
        golang.org/x/lint/golint loaded from golang.org/x/lint@v0.0.0-20190930215403-16217165b5de,
        but go 1.16 would select v0.0.0-20191125180803-fdd1cda4f05f
github.com/hwameistor/local-storage/pkg/apis imports
        k8s.io/apimachinery/pkg/runtime imports
        sigs.k8s.io/structured-merge-diff/v3/value imports
        gopkg.in/yaml.v2 tested by
        gopkg.in/yaml.v2.test imports
        gopkg.in/check.v1 imports
        github.com/kr/pretty loaded from github.com/kr/pretty@v0.1.0,
        but go 1.16 would select v0.2.1
github.com/hwameistor/local-storage/cmd/alerter imports
        sigs.k8s.io/controller-runtime/pkg/client/config tested by
        sigs.k8s.io/controller-runtime/pkg/client/config.test imports
        sigs.k8s.io/controller-runtime/pkg/log/zap imports
        go.uber.org/zap tested by
        go.uber.org/zap.test imports
        golang.org/x/lint/golint imports
        golang.org/x/lint loaded from golang.org/x/lint@v0.0.0-20190930215403-16217165b5de,
        but go 1.16 would select v0.0.0-20191125180803-fdd1cda4f05f
github.com/hwameistor/local-storage/pkg/scheduler imports
        k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
        k8s.io/kubernetes/pkg/controller/volume/scheduling imports
        k8s.io/apiserver/pkg/storage/etcd3 tested by
        k8s.io/apiserver/pkg/storage/etcd3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/embed imports
        github.com/grpc-ecosystem/grpc-gateway/runtime loaded from github.com/grpc-ecosystem/grpc-gateway@v1.9.5,
        but go 1.16 would select v1.12.1
github.com/hwameistor/local-storage/pkg/scheduler imports
        k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
        k8s.io/kubernetes/pkg/controller/volume/scheduling imports
        k8s.io/apiserver/pkg/storage/etcd3 tested by
        k8s.io/apiserver/pkg/storage/etcd3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/embed imports
        github.com/tmc/grpc-websocket-proxy/wsproxy loaded from github.com/tmc/grpc-websocket-proxy@v0.0.0-20170815181823-89b8d40f7ca8,
        but go 1.16 would select v0.0.0-20190109142713-0ad062ec5ee5
github.com/hwameistor/local-storage/pkg/scheduler imports
        k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
        k8s.io/kubernetes/pkg/controller/volume/scheduling imports
        k8s.io/apiserver/pkg/storage/etcd3 tested by
        k8s.io/apiserver/pkg/storage/etcd3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/embed imports
        go.etcd.io/bbolt loaded from go.etcd.io/bbolt@v1.3.3,
        but go 1.16 would select v1.3.4
github.com/hwameistor/local-storage/pkg/scheduler imports
        k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
        k8s.io/kubernetes/pkg/controller/volume/scheduling imports
        k8s.io/apiserver/pkg/storage/etcd3 tested by
        k8s.io/apiserver/pkg/storage/etcd3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/etcdserver/api/v3rpc imports
        github.com/grpc-ecosystem/go-grpc-middleware loaded from github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4,
        but go 1.16 would select v1.1.0
github.com/hwameistor/local-storage/pkg/scheduler imports
        k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
        k8s.io/kubernetes/pkg/controller/volume/scheduling imports
        k8s.io/apiserver/pkg/storage/etcd3 tested by
        k8s.io/apiserver/pkg/storage/etcd3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/embed imports
        github.com/grpc-ecosystem/grpc-gateway/runtime imports
        github.com/grpc-ecosystem/grpc-gateway/internal loaded from github.com/grpc-ecosystem/grpc-gateway@v1.9.5,
        but go 1.16 would select v1.12.1
github.com/hwameistor/local-storage/pkg/scheduler imports
        k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
        k8s.io/kubernetes/pkg/controller/volume/scheduling imports
        k8s.io/apiserver/pkg/storage/etcd3 tested by
        k8s.io/apiserver/pkg/storage/etcd3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/embed imports
        github.com/grpc-ecosystem/grpc-gateway/runtime imports
        github.com/grpc-ecosystem/grpc-gateway/utilities loaded from github.com/grpc-ecosystem/grpc-gateway@v1.9.5,
        but go 1.16 would select v1.12.1
github.com/hwameistor/local-storage/pkg/scheduler imports
        k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
        k8s.io/kubernetes/pkg/controller/volume/scheduling imports
        k8s.io/apiserver/pkg/storage/etcd3 tested by
        k8s.io/apiserver/pkg/storage/etcd3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/embed imports
        github.com/grpc-ecosystem/grpc-gateway/runtime imports
        google.golang.org/genproto/googleapis/api/httpbody loaded from google.golang.org/genproto@v0.0.0-20191220175831-5c49e3ecc1c1,
        but go 1.16 would select v0.0.0-20200117163144-32f20d992d24
github.com/hwameistor/local-storage/pkg/scheduler imports
        k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
        k8s.io/kubernetes/pkg/controller/volume/scheduling imports
        k8s.io/apiserver/pkg/storage/etcd3 tested by
        k8s.io/apiserver/pkg/storage/etcd3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/embed imports
        github.com/grpc-ecosystem/grpc-gateway/runtime imports
        google.golang.org/genproto/protobuf/field_mask loaded from google.golang.org/genproto@v0.0.0-20191220175831-5c49e3ecc1c1,
        but go 1.16 would select v0.0.0-20200117163144-32f20d992d24

To upgrade to the versions selected by go 1.16:
        go mod tidy -go=1.16 && go mod tidy -go=1.17
If reproducibility with go 1.16 is not needed:
        go mod tidy -compat=1.17
For other options, see:
        https://golang.org/doc/modules/pruning
```
It seems right?
What's go version support  exactly?

**Comment by sun7927** [comment]
> Hi, My go version is `go version go1.18rc1 darwin/amd64`,when I exec 'go mod tidy'(After I clone github.com/hwameistor/local-disk-manager)，I got this:
> 
> ```
> go: downloading github.com/onsi/ginkgo v1.12.1
> go: downloading github.com/onsi/gomega v1.10.1
> go: downloading k8s.io/apiextensions-apiserver v0.18.6
> go: downloading github.com/kr/pretty v0.1.0
> go: downloading github.com/grpc-ecosystem/grpc-gateway v1.9.5
> go: downloading github.com/tmc/grpc-websocket-proxy v0.0.0-20170815181823-89b8d40f7ca8
> go: downloading go.etcd.io/bbolt v1.3.3
> go: downloading github.com/gorilla/websocket v1.4.0
> go: downloading golang.org/x/lint v0.0.0-20190930215403-16217165b5de
> go: downloading golang.org/x/tools v0.1.1
> go: downloading golang.org/x/mod v0.4.2
> go: downloading sigs.k8s.io/structured-merge-diff v0.0.0-20190525122527-15d366b2352e
> go: downloading github.com/docker/docker v1.4.2-0.20200203170920-46ec8731fbce
> go: downloading google.golang.org/genproto v0.0.0-20200117163144-32f20d992d24
> go: downloading go.etcd.io/bbolt v1.3.4
> go: downloading github.com/grpc-ecosystem/grpc-gateway v1.12.1
> go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.1.0
> github.com/hwameistor/local-storage/cmd/scheduler imports
>         k8s.io/kubernetes/cmd/kube-scheduler/app imports
>         github.com/spf13/cobra loaded from github.com/spf13/cobra@v0.0.5,
>         but go 1.16 would select v1.0.0
> github.com/hwameistor/local-storage/cmd/scheduler imports
>         k8s.io/kubernetes/cmd/kube-scheduler/app imports
>         k8s.io/apiserver/pkg/util/term imports
>         github.com/docker/docker/pkg/term loaded from github.com/docker/docker@v0.7.3-0.20190327010347-be7ac8be2ae0,
>         but go 1.16 would select v1.4.2-0.20200203170920-46ec8731fbce
> github.com/hwameistor/local-storage/pkg/member/csi imports
>         github.com/container-storage-interface/spec/lib/go/csi imports
>         google.golang.org/grpc/status imports
>         google.golang.org/genproto/googleapis/rpc/status loaded from google.golang.org/genproto@v0.0.0-20191220175831-5c49e3ecc1c1,
>         but go 1.16 would select v0.0.0-20200117163144-32f20d992d24
> github.com/hwameistor/local-storage/pkg/scheduler imports
>         k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
>         k8s.io/component-base/metrics imports
>         github.com/blang/semver loaded from github.com/blang/semver@v3.5.0+incompatible,
>         but go 1.16 would select v3.5.1+incompatible
> github.com/hwameistor/local-storage/cmd/scheduler imports
>         k8s.io/kubernetes/cmd/kube-scheduler/app imports
>         k8s.io/apiserver/pkg/server/routes imports
>         k8s.io/kube-openapi/pkg/handler imports
>         github.com/NYTimes/gziphandler loaded from github.com/NYTimes/gziphandler@v0.0.0-20170623195520-56545f4a5d46,
>         but go 1.16 would select v1.1.1
> github.com/hwameistor/local-storage/cmd/scheduler imports
>         k8s.io/kubernetes/cmd/kube-scheduler/app imports
>         k8s.io/apiserver/pkg/util/term imports
>         github.com/docker/docker/pkg/term imports
>         github.com/docker/docker/pkg/term/windows loaded from github.com/docker/docker@v0.7.3-0.20190327010347-be7ac8be2ae0,
>         but go 1.16 would select v1.4.2-0.20200203170920-46ec8731fbce
> github.com/hwameistor/local-storage/pkg/member/csi imports
>         github.com/container-storage-interface/spec/lib/go/csi imports
>         google.golang.org/grpc/codes tested by
>         google.golang.org/grpc/codes.test imports
>         google.golang.org/genproto/googleapis/rpc/code loaded from google.golang.org/genproto@v0.0.0-20191220175831-5c49e3ecc1c1,
>         but go 1.16 would select v0.0.0-20200117163144-32f20d992d24
> github.com/hwameistor/local-storage/pkg/member/csi imports
>         github.com/container-storage-interface/spec/lib/go/csi imports
>         google.golang.org/grpc/status tested by
>         google.golang.org/grpc/status.test imports
>         google.golang.org/genproto/googleapis/rpc/errdetails loaded from google.golang.org/genproto@v0.0.0-20191220175831-5c49e3ecc1c1,
>         but go 1.16 would select v0.0.0-20200117163144-32f20d992d24
> github.com/hwameistor/local-storage/pkg/scheduler imports
>         k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
>         k8s.io/kubernetes/pkg/controller/volume/scheduling imports
>         k8s.io/apiserver/pkg/storage/etcd3 tested by
>         k8s.io/apiserver/pkg/storage/etcd3.test imports
>         github.com/coreos/pkg/capnslog loaded from github.com/coreos/pkg@v0.0.0-20180108230652-97fdf19511ea,
>         but go 1.16 would select v0.0.0-20180928190104-399ea9e2e55f
> github.com/hwameistor/local-storage/cmd/alerter imports
>         sigs.k8s.io/controller-runtime/pkg/client/config tested by
>         sigs.k8s.io/controller-runtime/pkg/client/config.test imports
>         sigs.k8s.io/controller-runtime/pkg/log/zap imports
>         go.uber.org/zap tested by
>         go.uber.org/zap.test imports
>         golang.org/x/lint/golint loaded from golang.org/x/lint@v0.0.0-20190930215403-16217165b5de,
>         but go 1.16 would select v0.0.0-20191125180803-fdd1cda4f05f
> github.com/hwameistor/local-storage/pkg/apis imports
>         k8s.io/apimachinery/pkg/runtime imports
>         sigs.k8s.io/structured-merge-diff/v3/value imports
>         gopkg.in/yaml.v2 tested by
>         gopkg.in/yaml.v2.test imports
>         gopkg.in/check.v1 imports
>         github.com/kr/pretty loaded from github.com/kr/pretty@v0.1.0,
>         but go 1.16 would select v0.2.1
> github.com/hwameistor/local-storage/cmd/alerter imports
>         sigs.k8s.io/controller-runtime/pkg/client/config tested by
>         sigs.k8s.io/controller-runtime/pkg/client/config.test imports
>         sigs.k8s.io/controller-runtime/pkg/log/zap imports
>         go.uber.org/zap tested by
>         go.uber.org/zap.test imports
>         golang.org/x/lint/golint imports
>         golang.org/x/lint loaded from golang.org/x/lint@v0.0.0-20190930215403-16217165b5de,
>         but go 1.16 would select v0.0.0-20191125180803-fdd1cda4f05f
> github.com/hwameistor/local-storage/pkg/scheduler imports
>         k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
>         k8s.io/kubernetes/pkg/controller/volume/scheduling imports
>         k8s.io/apiserver/pkg/storage/etcd3 tested by
>         k8s.io/apiserver/pkg/storage/etcd3.test imports
>         go.etcd.io/etcd/integration imports
>         go.etcd.io/etcd/embed imports
>         github.com/grpc-ecosystem/grpc-gateway/runtime loaded from github.com/grpc-ecosystem/grpc-gateway@v1.9.5,
>         but go 1.16 would select v1.12.1
> github.com/hwameistor/local-storage/pkg/scheduler imports
>         k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
>         k8s.io/kubernetes/pkg/controller/volume/scheduling imports
>         k8s.io/apiserver/pkg/storage/etcd3 tested by
>         k8s.io/apiserver/pkg/storage/etcd3.test imports
>         go.etcd.io/etcd/integration imports
>         go.etcd.io/etcd/embed imports
>         github.com/tmc/grpc-websocket-proxy/wsproxy loaded from github.com/tmc/grpc-websocket-proxy@v0.0.0-20170815181823-89b8d40f7ca8,
>         but go 1.16 would select v0.0.0-20190109142713-0ad062ec5ee5
> github.com/hwameistor/local-storage/pkg/scheduler imports
>         k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
>         k8s.io/kubernetes/pkg/controller/volume/scheduling imports
>         k8s.io/apiserver/pkg/storage/etcd3 tested by
>         k8s.io/apiserver/pkg/storage/etcd3.test imports
>         go.etcd.io/etcd/integration imports
>         go.etcd.io/etcd/embed imports
>         go.etcd.io/bbolt loaded from go.etcd.io/bbolt@v1.3.3,
>         but go 1.16 would select v1.3.4
> github.com/hwameistor/local-storage/pkg/scheduler imports
>         k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
>         k8s.io/kubernetes/pkg/controller/volume/scheduling imports
>         k8s.io/apiserver/pkg/storage/etcd3 tested by
>         k8s.io/apiserver/pkg/storage/etcd3.test imports
>         go.etcd.io/etcd/integration imports
>         go.etcd.io/etcd/etcdserver/api/v3rpc imports
>         github.com/grpc-ecosystem/go-grpc-middleware loaded from github.com/grpc-ecosystem/go-grpc-middleware@v1.0.1-0.20190118093823-f849b5445de4,
>         but go 1.16 would select v1.1.0
> github.com/hwameistor/local-storage/pkg/scheduler imports
>         k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
>         k8s.io/kubernetes/pkg/controller/volume/scheduling imports
>         k8s.io/apiserver/pkg/storage/etcd3 tested by
>         k8s.io/apiserver/pkg/storage/etcd3.test imports
>         go.etcd.io/etcd/integration imports
>         go.etcd.io/etcd/embed imports
>         github.com/grpc-ecosystem/grpc-gateway/runtime imports
>         github.com/grpc-ecosystem/grpc-gateway/internal loaded from github.com/grpc-ecosystem/grpc-gateway@v1.9.5,
>         but go 1.16 would select v1.12.1
> github.com/hwameistor/local-storage/pkg/scheduler imports
>         k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
>         k8s.io/kubernetes/pkg/controller/volume/scheduling imports
>         k8s.io/apiserver/pkg/storage/etcd3 tested by
>         k8s.io/apiserver/pkg/storage/etcd3.test imports
>         go.etcd.io/etcd/integration imports
>         go.etcd.io/etcd/embed imports
>         github.com/grpc-ecosystem/grpc-gateway/runtime imports
>         github.com/grpc-ecosystem/grpc-gateway/utilities loaded from github.com/grpc-ecosystem/grpc-gateway@v1.9.5,
>         but go 1.16 would select v1.12.1
> github.com/hwameistor/local-storage/pkg/scheduler imports
>         k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
>         k8s.io/kubernetes/pkg/controller/volume/scheduling imports
>         k8s.io/apiserver/pkg/storage/etcd3 tested by
>         k8s.io/apiserver/pkg/storage/etcd3.test imports
>         go.etcd.io/etcd/integration imports
>         go.etcd.io/etcd/embed imports
>         github.com/grpc-ecosystem/grpc-gateway/runtime imports
>         google.golang.org/genproto/googleapis/api/httpbody loaded from google.golang.org/genproto@v0.0.0-20191220175831-5c49e3ecc1c1,
>         but go 1.16 would select v0.0.0-20200117163144-32f20d992d24
> github.com/hwameistor/local-storage/pkg/scheduler imports
>         k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1 imports
>         k8s.io/kubernetes/pkg/controller/volume/scheduling imports
>         k8s.io/apiserver/pkg/storage/etcd3 tested by
>         k8s.io/apiserver/pkg/storage/etcd3.test imports
>         go.etcd.io/etcd/integration imports
>         go.etcd.io/etcd/embed imports
>         github.com/grpc-ecosystem/grpc-gateway/runtime imports
>         google.golang.org/genproto/protobuf/field_mask loaded from google.golang.org/genproto@v0.0.0-20191220175831-5c49e3ecc1c1,
>         but go 1.16 would select v0.0.0-20200117163144-32f20d992d24
> 
> To upgrade to the versions selected by go 1.16:
>         go mod tidy -go=1.16 && go mod tidy -go=1.17
> If reproducibility with go 1.16 is not needed:
>         go mod tidy -compat=1.17
> For other options, see:
>         https://golang.org/doc/modules/pruning
> ```
> 
> It seems right? What's go version support exactly?

please go with 1.17

**Comment by niulechuan** [comment]
Friendly cc: @angel0507 Could you take a look？

**Comment by angel0507** [comment]
@jiuker @sun7927   I think you can exec `go mod tidy -compat=1.17` , it takes effect in my dev enviroment .

**Comment by jiuker** [comment]
> @jiuker @sun7927 I think you can exec `go mod tidy -compat=1.17` , it takes effect in my dev enviroment . go verion in my environment : go version go1.17.5 darwin/arm64

Yes。it work! Why need two version?

**Comment by angel0507** [comment]
> 

I think The -compat flag allows that version to be overridden to support older (or only newer) versions, up to the version specified by the go directive in the go.mod file.

**Comment by angel0507** [comment]
@jiuker I think The -compat flag allows that version to be overridden to support older (or only newer) versions, up to the version specified by the go directive in the go.mod file. at last we hope more go versions  can be suited
