### ISSUE TITLE
helm install error

### ISSUE THREAD

**Issue by xulongju** [hwameistor/local-storage#33]
Hi：
I use helm to deploy hwameister

# error log
## local-disk-manager:v0.0.2
```
  Warning  Failed     3m11s (x5 over 4m36s)  kubelet            Error: failed to start container "local-disk-manager": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/local-disk-manager": stat /local-disk-manager: no such file or directory: unknown
```

**Comment by SSmallMonster** [comment]
> Hi： I use helm to deploy hwameister
> 
> # error log
> ## local-disk-manager:v0.0.2
> ```
>   Warning  Failed     3m11s (x5 over 4m36s)  kubelet            Error: failed to start container "local-disk-manager": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/local-disk-manager": stat /local-disk-manager: no such file or directory: unknown
> ```

Could you provide the image digest of local disk manager(v0.0.2)?  The correct one should be:
`sha256:a5d4401a0bd10a4376df71e324316a53e9f052da8401b11c6d10fea20fb5e228`

How to query a image digest:
```
docker image inspect ghcr.io/hwameistor/local-disk-manager:v0.0.2 -f='{{.RepoDigests}}'
```

**Comment by xulongju** [comment]
Hi,
<img width="1914" alt="image" src="https://user-images.githubusercontent.com/20881910/157010205-bda38b68-1dd6-41b7-9020-e5862d119ec5.png">

**Comment by xulongju** [comment]
Hi，
I redeployed it once, is ok，thank you。
