### ISSUE TITLE
Should LS  be able to running on master?

### ISSUE THREAD

**Issue by niulechuan** [hwameistor/local-storage#45]
Should LS  be able to running on master?

I realize in helm-charts, LS was be able to runing on master already.

https://github.com/hwameistor/helm-charts/blob/4d7e7399ca551b646a4c0669481f60443e34b33a/charts/hwameistor/templates/local-storage-driver.yaml#L137-L148

**Comment by angel0507** [comment]
yeah ,LS was able to running on master node  as well .
